export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const STATS_HAB_BY_HAIRCOLOR_SUCCESS = "STATS_HAB_BY_HAIRCOLOR_SUCCESS";
export const STATS_HAB_BY_HAIRCOLOR_FAIL = "STATS_HAB_BY_HAIRCOLOR_FAIL";
export const STATS_HAB_BY_PROF_SUCCESS = "STATS_HAB_BY_PROF_SUCCESS";
export const STATS_HAB_BY_PROF_FAIL = "STATS_HAB_BY_PROF_FAIL";

export const SEARCH_HABITANTS_SUCCESS = "SEARCH_HABITANTS_SUCCESS";
export const SEARCH_HABITANTS_FAIL = "SEARCH_HABITANTS_FAIL";

export const LOAD_HAB_PROFESSIONS_SUCCESS = "LOAD_HAB_PROFESSIONS_SUCCESS";
export const LOAD_HAB_HAIR_COLORS_SUCCESS = "LOAD_HAB_HAIR_COLORS_SUCCESS";

export const REGISTERME_AS_HAB_SUCCESS = "REGISTERME_AS_HAB_SUCCESS";
export const REGISTERME_AS_HAB_FAIL = "REGISTERME_AS_HAB_FAIL";
export const REGISTERME_AS_HAB_EXISTS_FAIL = "REGISTERME_AS_HAB_EXISTS_FAIL";

export const UNREGISTERME_AS_HAB_SUCCESS = "UNREGISTERME_AS_HAB_SUCCESS";
export const UNREGISTERME_AS_HAB_FAIL = "UNREGISTERME_AS_HAB_FAIL";

export const LOAD_MY_HAB_DETAILS_SUCCESS = "LOAD_MY_HAB_DETAILS_SUCCESS";
export const LOAD_MY_HAB_DETAILS_FAIL = "LOAD_MY_HAB_DETAILS_FAIL";

export const SAVE_MY_HAB_DETAILS_SUCCESS = "SAVE_MY_HAB_DETAILS_SUCCESS";
export const SAVE_MY_HAB_DETAILS_FAIL = "SAVE_MY_HAB_DETAILS_FAIL";

export const LOAD_MY_FRIENDS_SUCCESS = "LOAD_MY_FRIENDS_SUCCESS";
export const LOAD_MY_FRIENDS_FAIL = "LOAD_MY_FRIENDS_FAIL";

export const ADD_FRIEND_SUCCESS = "ADD_FRIEND_SUCCESS";
export const ADD_FRIEND_FAIL = "ADD_FRIEND_FAIL";

export const REMOVE_FRIEND_SUCCESS = "REMOVE_FRIEND_SUCCESS";
export const REMOVE_FRIEND_FAIL = "REMOVE_FRIEND_FAIL";
